### ISSUE TITLE
Issue starting mosquitto error: unable to create websockets listener on port 9883

### ISSUE THREAD

**Issue by dannyvee** [grafolean/grafolean#45]
**Steps To Reproduce**
docker-compose up -d (using the included docker-compose.yml)

**Whan went wrong**
Stack fails to start, docker opens port 80 but due to mosquitto in a restart loop, never responds to traffic.

**Expected behavior**
All containers to start up healthy.

**Software versions:**
 - Docker version [Docker version 26.0.0, build 2ae903e
 - Docker Compose version v2.25.0
 - Browser [e.g. firefox, chrome, safari] - if applicable
 - Grafolean Version latest

**Additional context**
mosquitto                    | time="2024-03-29T19:24:33Z" level=info msg="log_dest unknown, using default stderr"
mosquitto                    | time="2024-03-29T19:24:33Z" level=warning msg="unknown or empty hasher, defaulting to PBKDF2"
mosquitto                    | time="2024-03-29T19:24:33Z" level=info msg="Backend registered: JWT"
mosquitto                    | time="2024-03-29T19:24:33Z" level=info msg="redisCache activated"
mosquitto                    | time="2024-03-29T19:24:33Z" level=info msg="started go-cache"
mosquitto                    | time="2024-03-29T19:24:33Z" level=info msg="flushed go-cache"
mosquitto                    | 1711740273: Error: Unable to create websockets listener on port 9883.

**Comment by grafolean** [comment]
The usual reason for such refusal to start is that something else is already on that port (9883). However, with the default `docker-compose.yml` the containers start in their own Docker network, so this should never happen.

Quick search didn't reveal anything useful. Is there something special in the way that you have performed the installation? Did you change `docker-compose.yml` in any way?

**Comment by dannyvee** [comment]
No the docker-compose.yml was curl'd from the instruction on the README.md page. 

This is a fresh install of Rocky 9.3, I made sure nothing on the host was listening on that port, unfortunately because the container restarts I am unable to netstat from within the container.

I couldn't find anything on Google related to the issue either. Just some things about HomeAssistant but seemingly unrelated. 

First time I have ever ran into a container that failed to open a socket on a brand new docker network. I might try a different distro to see if its something related to the Rocky kernel. I'll keep you posted.

**Comment by Jayasankar-Surendran** [comment]
I am facing the same issue with my Portainer setup.
Created as a Stack with ENV files.

Observations:
1. Sometimes the NGINX works and gives the GUI. I could login and in less than 1 minute GUI back to login page. However, sometimes it shows the log "INFO exited: nginx (exit status 1; not expected)". Here I think, as mentioned in other Issue, it couldnt find the "mosquitto" and as I restart the container "mosquitto" it will provide the login GUI; however, I could see the following logs.

```
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
2024-06-28 16:06:13 | ERR | MQTT publishing: exception Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_executor/executor.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/ctx.py", line 158, in wrapper
    return f(*args, **kwargs)
  File "./api/common.py", line 87, in _bg_mqtt_publish
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/publish.py", line 167, in multiple
    client.connect(hostname, port, keepalive)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
192.168.240.7 - - [28/Jun/2024:16:06:25 +0000] "GET / HTTP/1.1" 200 1235 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" rt=0.000 urt=-
192.168.240.7 - - [28/Jun/2024:16:06:25 +0000] "GET /api/status/info HTTP/1.1" 200 192 "http://192.168.240.225:8092/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" rt=0.004 urt=0.003
192.168.240.7 - - [28/Jun/2024:16:06:25 +0000] "GET /api/status/info HTTP/1.1" 200 192 "http://192.168.240.225:8092/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" rt=0.002 urt=0.002
2024-06-28 16:07:07 | INF | Superuser auth token not available or expired, refreshing.
172.18.0.7 - - [28/Jun/2024:16:07:07 +0000] "GET /api/accounts/?b=c71ec7da-2798-4c13-986a-4ad9a7f971b7 HTTP/1.1" 200 56 "-" "python-requests/2.22.0" rt=0.046 urt=0.046
172.18.0.7 - - [28/Jun/2024:16:07:07 +0000] "GET /api/accounts/1472614297/entities/?b=c71ec7da-2798-4c13-986a-4ad9a7f971b7 HTTP/1.1" 200 174 "-" "python-requests/2.22.0" rt=0.020 urt=0.020
2024-06-28 16:07:07 | INF | Superuser auth token not available or expired, refreshing.
172.18.0.7 - - [28/Jun/2024:16:07:07 +0000] "GET /api/accounts/1472614297/entities/525378578?b=c71ec7da-2798-4c13-986a-4ad9a7f971b7 HTTP/1.1" 200 162 "-" "python-requests/2.22.0" rt=0.017 urt=0.018
2024-06-28 16:07:10 | ERR | MQTT publishing: exception Traceback (most recent call last):
```

2. Mosquitto always has the same error that it can not open the socket.

```
time="2024-06-28T16:03:55Z" level=info msg="flushed go-cache"
1719590635: Error: Unable to create websockets listener on port 9883.
time="2024-06-28T16:04:56Z" level=info msg="log_dest unknown, using default stderr"
time="2024-06-28T16:04:56Z" level=warning msg="unknown or empty hasher, defaulting to PBKDF2"
time="2024-06-28T16:04:56Z" level=info msg="Backend registered: JWT"
time="2024-06-28T16:04:56Z" level=info msg="redisCache activated"
time="2024-06-28T16:04:56Z" level=info msg="started go-cache"
time="2024-06-28T16:04:56Z" level=info msg="flushed go-cache"

```
